### PR TITLE
Smooth map scrolling, out of bounds map scrolling, and more

### PR DESCRIPTION
**Pull request by tolmar**
Adds per-pixel scrolling to the map editor. This allows the screen to scroll past the map bounds. This in turn lets the door editor jump to consistent coordinates.

Also contains a lot of cleanup. The final commit is the new stuff.

Please check that this works before approving - I might've missed adding a file due to the dumb setup I'm using. I also might've missed a UI flow when testing the change.

### CODE REVIEW

**Comment by brentjs0** [comment]
The right-click context menu is being placed incorrectly:
image

The issue is especially pronounced when the viewport is scrolled beyond the edge of the map:
image

**Comment by tolmar** [comment]
Good catch. I actually fixed this bug in the Zoom PR (https://github.com/pk-hack/EbProjectEditor/pull/7/commits/5b57081f5f372cbaf35e8a4e785f3ef1a8902ab2) 

Do you want me to try to port the fix back, or just wait for zoom and push both?

**Comment by brentjs0** [comment]
I'll just review and test them both together.

**Review by brentjs0 — APPROVED** [review]
Looks good to go if merged with #7.

**Pull request merged**
