### PR TITLE
Click and drag to place tiles

### PR DESCRIPTION
**Pull request by tolmar**
Pretty straightforward, makes the tile editor a lot more usable.

(Branch contains the enemy viewer branch; I don't know how to make github handle showing sequential branches better.)

### CODE REVIEW

**Comment by brentjs0** [comment]
> Pretty straightforward, makes the tile editor a lot more usable.
> 
> (Branch contains the enemy viewer branch; I don't know how to make github handle showing sequential branches better.)

You can change the base branch from **main** to **enemy-viewer**.
But now that **enemy-viewer** is merged to **main**, you should instead merge the latest from main into **drag** and do a `git push`.

Sorry if any of this is stuff you already know.

**Comment by tolmar** [comment]
Nah, it's stuff I don't know. I'm used to perforce, not git, and github adds its own layer of idiosyncrasies to git.
I created all of these branches by forking one of the others from github's UI. That doesn't set the base branch properly?

**Comment by tolmar** [comment]
Looks properly synced up for now.

Also wanted to mention that I removed the un-select sector code from this because it was constantly toggling on/off while you drag, and deselecting sectors is kind of a bad feature in the first place. (Adds an extra state to the code and UI, doesn't really give the user any capabilities.)

**Comment by brentjs0** [comment]
> Nah, it's stuff I don't know. I'm used to perforce, not git, and github adds its own layer of idiosyncrasies to git. I created all of these branches by forking one of the others from github's UI. That doesn't set the base branch properly?

> Nah, it's stuff I don't know. I'm used to perforce, not git, and github adds its own layer of idiosyncrasies to git. I created all of these branches by forking one of the others from github's UI. That doesn't set the base branch properly?

The base branch listed above is **pk-hack:main** (and has been since it was created), so apparently not.

**Comment by tolmar** [comment]
Got merged as part of teleport edit.

**Pull request closed without merging**
